# Generated by Django 2.0.7 on 2018-07-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_id', models.IntegerField(null=True)),
                ('temp', models.FloatField(null=True)),
                ('ber', models.FloatField(null=True)),
                ('created', models.DateTimeField(blank=True)),
            ],
        ),
    ]
