# Generated by Django 2.0.7 on 2018-07-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
